### ISSUE TITLE
PayPal Integral evolution/PayPal Plus

### ISSUE THREAD

**Issue by ukbaz2** [thirtybees/paypal#11]
Hi - trying ths out on a test site and PayPal Plus getting forbidden Icon in iframe no matter what country is selected.- even Germany

Am UK based - when will it support iframe checkut in UK?
Thanks
Baz

**Comment by firstred** [comment]
> Hi - trying ths out on a test site and PayPal Plus getting forbidden Icon in iframe no matter what country is selected.- even Germany

That's likely a server setting. It probably sends some additional CORS headers. Headers like `X-Frame-Options` can dictate which iframes are allowed and which aren't.

> Am UK based - when will it support iframe checkut in UK?

No, we have not restored the Hosted Solutions checkouts. PayPal wants to replace these with Braintree in the near future.

**Comment by firstred** [comment]
If you need all these features, I recommend to stay on the 3.11.4 PS version and not update the module to a tb one. If you have already updated the module, remove the module folder and unpack the 3.11.4 module at the same place. It will switch seamlessly.

**Comment by ukbaz2** [comment]
Hi Michael - thanks for the quick reply - any idea when the module will support PayPal Payments Pro?

Thanks again
Baz

**Comment by firstred** [comment]
Let me see. We were waiting for an official statement from PayPal on which services were going to be discontinued.

**Comment by firstred** [comment]
Okay, looks like we can add Payments Pro (uk/us/canada) and Payflow Gateway (us/canada).
But really no idea when we are going to add it, documentation for these services is really scarse now. I will schedule then anyway, but expect to have to wait at least a month before we have those services available in the module.

**Comment by firstred** [comment]
Them*

**Comment by ukbaz2** [comment]
Thanks Michael - good to hear - the Prestashop PayPal module has issues!

**Comment by firstred** [comment]
Looks like Payflow Gateway will be discontinued as well, which limits future support to just Payments Pro. If you need a better module for that right away you can use this paid one: http://www.presto-changeo.com/en/prestashop-payment-modules/88-prestashop-paypal-pro-module.html

**Comment by firstred** [comment]
I'm not sure if we can add it. We have been trying to test it recently, but it looks like the sandbox environment is down and no longer used. Will keep you informed when we find something.
