### ISSUE TITLE
Documentation link doesn't work

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/paypal#13]
The documentation link points to an incorrect url.

It point to:
https://docs.thirtybees.com/merchants-guide/native-modules/paypal/

This should be:
https://docs.thirtybees.com/native-modules/paypal/

![thirty14](https://user-images.githubusercontent.com/13930107/30966248-95457010-a458-11e7-8b2a-da0fe99443c0.jpg)

**Comment by Dh42** [comment]
Thanks, I updated it, https://github.com/thirtybees/paypal/commit/74451550e42c9412a48fe4663b24998c13e000ce
