### ISSUE TITLE
Paypal not showing among payment options

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/paypal#14]
When I enable Paypal I don't see it among the payment options. However, I do see a Paypal checkout button to the right (next to the address). Maybe this has something to do with my one column layout?

![thirty15](https://user-images.githubusercontent.com/13930107/31022711-f3706866-a539-11e7-8c6e-ac2bae518a58.jpg)

**Comment by Dh42** [comment]
Do you have website payments standard selected? That is what paypal being tied to the bottom requires.

**Comment by musicpanda** [comment]
That was indeed the problem. Thanks.
