### ISSUE TITLE
PayPalRestApi.php contains invalid single quote characters

### ISSUE THREAD

**Issue by techjp** [thirtybees/paypal#24]
On line 404 of the PayPalRestApi.php file it says:

`$details[‘shipping_discount’] = number_format(abs($remaining - $giftWithoutTax), 2);`

It should say:

`$details['shipping_discount'] = number_format(abs($remaining - $giftWithoutTax), 2);`

shipping_discount is surrounded by formatted single quote characters. I do not know if these are entirely invalid for PHP or not but in my text editor they don't seem to work properly as single quote characters.

Could this be the reason why the PayPal rounding calculation system never worked properly? @Dh42, any thoughts?

**Comment by getdatakick** [comment]
Fixed in commit f61f0a8980258a4dcb2019fb018304737502cc9b
