### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by Coachonko** [thirtybees/paypal#34]
​
While I was trying to solve [this problem](https://forum.thirtybees.com/topic/5852-smtp-permission-denied-13/) I found the following errors in the php-fpm logs
```
[08-Oct-2022 08:30:59 Europe/Brussels] PHP Notice:  Undefined variable: process in /var/www/domain.com/html/modules/paypal/paypal.php on line 935
```
This is filling the /var/log/php-fpm/www-error.log file

I am on Euro Linux 8.6, PHP 7.4, thirty bees 1.3 stable

​

**Comment by getdatakick** [comment]
This was fixed by commit c71752216dd23ca77743bf24c14f130cd9b5b2c8. Will be part of the next release
