### ISSUE TITLE
Paypal module (with new API app) not working after cloning site

### ISSUE THREAD

**Issue by holybladder** [thirtybees/paypal#38]
I cloned my Thirty Bees instance to a new domain, updated all the shop information and created a new clean Paypal API app, but the Paypal module on the new site won't connect - see screenshot. First time Plus and Checkout did show as active with just Standard missing, but after a couple of retries all three are showing as missing. I've removed and reinstalled the Paypal module twice and recreated the API app six or seven times with different names, and I've very carefully checked the Client ID and Secret for whitespace or errors, even copy pasted both into a text file to check alongside each other.

![Screenshot from 2022-10-18 15-06-19](https://user-images.githubusercontent.com/2101939/197511009-ce9e53b9-3a16-4e5b-9e20-855167a88604.png)

Paypal support say: "After further review I am not seeing any issues with the Client IDs you provided, or with your PayPal account. Please make sure on the new integration that you did not add any additional white space when pasting the Client ID and Secret. If this is not the case, you will then want to reach out to thirty bees support so they can check why the error is being generated since you are using a different Client ID."

Module is fully updated and I and my host have checked all logs and found no errors relating to the module.

**Comment by holybladder** [comment]
> Try edit file `modules/paypal/classes/PayPalRestApi.php` and change line ~599 from
> 
> ```
> $name = "thirtybees_{$shop_id}_{$type_id}_v2";
> ```
> 
> to
> 
> ```
> $name = "thirtybees_{$shop_id}_{$type_id}_v3";
> ```

That fixed it, you absolute legend! You have no idea what a relief that is :smile: I updated the module last week, is that a very new change?

**Comment by getdatakick** [comment]
Not a fix, but a workaround.

There seems to be a bug in deletion of 'web experience profile' (if the profile was created on different tb installation).

The profile should should probably exists per domain/module installation
