### ISSUE TITLE
Console log print necessary? 

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/paypal#8]
Is it necessary to print this log:
ppxo_setup_production Object {timestamp: 1494233727558, windowID: "12529b1d61", pageID: "fbc6a007cc", host: "localhost", path: "/myshop/women/dresses/evening-dresses/printed-dress"…}

**Comment by firstred** [comment]
Yup, it's necessary. I guess PayPal's customer service wants it for debug purposes or something.

**Comment by yaniv14** [comment]
Ok, thanks for clarifying
